version: "3.8"
services:
  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: amir1221
      POSTGRES_DB: freegate_db
    volumes:
      - freegate-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./backend
    depends_on:
      - db
    ports:
      - 8080:8080
  web:
    build:
      context: ./freegate-frontend
      dockerfile: dockerfile.prod
    ports:
      - 80:80
  dbms:
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=mp.amir@yahoo.com
      - PGADMIN_DEFAULT_PASSWORD=amir1221
    ports:
      - 5050:80
volumes:
  - freegate-db:
